spring:
  application:
    name: r024network
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/r024netframe?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: UILE1357?
server:
  port: 8080
jwt:
  secret: LmPkEAze5jbwndNh/INYLrUMu51113Mz3N8QejiVnuE=


